### ISSUE TITLE
Missing Dependency in Binary Build

### ISSUE THREAD

**Issue by sjiherzig** [JPL-IMCE/gov.nasa.jpl.imce.oml.converters#3]
Running the binary fails with the following:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at org.eclipse.xtext.service.AbstractGenericModule.<clinit>(AbstractGenericModule.java:28)
	at org.eclipse.xtext.ecore.EcoreSupport.createGuiceModule(EcoreSupport.java:45)
	at org.eclipse.xtext.resource.generic.AbstractGenericResourceSupport.getGuiceModule(AbstractGenericResourceSupport.java:68)
	at org.eclipse.xtext.resource.generic.AbstractGenericResourceSupport.registerServices(AbstractGenericResourceSupport.java:55)
	at org.eclipse.xtext.ecore.EcoreSupportStandaloneSetup.<init>(EcoreSupportStandaloneSetup.java:23)
	at org.eclipse.xtext.ecore.EcoreSupportStandaloneSetup.setup(EcoreSupportStandaloneSetup.java:19)
	at org.eclipse.emf.ecore.xcore.XcoreStandaloneSetup.createInjectorAndDoEMFRegistration(XcoreStandaloneSetup.java:64)
	at org.eclipse.emf.ecore.xcore.XcoreStandaloneSetup.doSetup(XcoreStandaloneSetup.java:58)
	at gov.nasa.jpl.imce.oml.converters.utils.OMLResourceSet$.initializeResourceSet(OMLResourceSet.scala:37)
	at gov.nasa.jpl.imce.oml.converters.OMLConverterFromTextualConcreteSyntax$.convert(OMLConverterFromTextualConcreteSyntax.scala:60)
	at gov.nasa.jpl.imce.oml.converters.OMLConverter$.main(OMLConverter.scala:63)
	at gov.nasa.jpl.imce.oml.converters.OMLConverter.main(OMLConverter.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
```

Checking the `lib` directory of the tar resource containing the binary build, it seems that log4j is indeed missing. **Update:** *this is incorrect - there is a log4j.log4j-1.2.17.jar*

To be done is:
* Add log4j to `lib`
* Update classpath in script to include this library

**Comment by sjiherzig** [comment]
Turns out the log4j.log4j-1.2.17.jar in `lib` contains only source files (i.e., all .java, no .class; and includes build scripts). Strangely, replacing this jar with a binary build also does not alleviate the problem.

Checked if the classpath is perhaps not passed correctly, but that also doesn't seem to be the problem...

**Comment by NicolasRouquette** [comment]
This may be related to dependency filtering to avoid dragging in old log4j libraries.
See: https://github.com/JPL-IMCE/gov.nasa.jpl.imce.oml.converters/blob/master/build.sbt#L91

At the `sbt` prompt, `show coursierDependencyTree` or `show coursierDependencyInvertedTree` can help determine where log4j comes from.

**Comment by NicolasRouquette** [comment]
During packaging, there were two `log4j` artifacts:
- `log4j-1.2.17.zip`
- `log4j-1.2.17.jar`

The former contains a source `log4j-1.2.17.jar`, which overwrote the later.

The fix is to filter out the source archive.

```
    mappings in Universal := {
      val prev = (mappings in Universal).value
      prev.filter { case (file, name) =>
        !(file.name.endsWith("log4j-1.2.17.zip") && name == "lib/log4j.log4j-1.2.17.jar")
      }
    },
```
