### ISSUE TITLE
Eclipse URI NPE

### ISSUE THREAD

**Issue by NicolasRouquette** [JPL-IMCE/gov.nasa.jpl.imce.oml.converters#59]
```
[563] $ ./scripts/vocabulary-authored-imce.sh 
/opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows
# Start from the branch: master of the gov.nasa.jpl.imce.caesar.workflows repo
Cloning into 'gov.nasa.jpl.imce.caesar.workflows'...
remote: Counting objects: 1361, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 1361 (delta 15), reused 40 (delta 9), pack-reused 1311
Receiving objects: 100% (1361/1361), 1.18 MiB | 0 bytes/s, done.
Resolving deltas: 100% (519/519), done.
# Checkout the branch: vocabulary/authored/imce, creating it it does not exist or merging it with master otherwise.
Branch vocabulary/authored/imce set up to track remote branch vocabulary/authored/imce from origin.
Switched to a new branch 'vocabulary/authored/imce'
Already up-to-date.
On branch vocabulary/authored/imce
Your branch is up-to-date with 'origin/vocabulary/authored/imce'.
nothing to commit, working tree clean
# Get the branch: feature/IMCEIS-1715-create-temporary-branch-of-ontologie of the IMCE ontologies.public repo
Cloning into 'gov.nasa.jpl.imce.ontologies.public'...
remote: Counting objects: 2865, done.
remote: Compressing objects: 100% (175/175), done.
remote: Total 2865 (delta 192), reused 346 (delta 166), pack-reused 2481
Receiving objects: 100% (2865/2865), 2.84 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1751/1751), done.
Branch feature/IMCEIS-1715-create-temporary-branch-of-ontologie set up to track remote branch feature/IMCEIS-1715-create-temporary-branch-of-ontologie from origin.
Switched to a new branch 'feature/IMCEIS-1715-create-temporary-branch-of-ontologie'
On branch feature/IMCEIS-1715-create-temporary-branch-of-ontologie
Your branch is up-to-date with 'origin/feature/IMCEIS-1715-create-temporary-branch-of-ontologie'.
nothing to commit, working tree clean
# Clear the destination folder & copy IMCE vocabularies
Resolved 60 files across 1 catalog rewrite rules.
=> 60 resolved based on the rewrite rule for: http://
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/math/math-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/math/math.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/oml/oml.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/skeleton/skeleton-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/skeleton/skeleton.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/www.w3.org/2001/XMLSchema.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/discipline/fault-management/fault-management-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/discipline/fault-management/fault-management.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/discipline/fse/fse-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/discipline/fse/fse.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/discipline/mechanical/mechanical-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/discipline/mechanical/mechanical.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/discipline/ontological-behavior/ontological-behavior-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/discipline/ontological-behavior/ontological-behavior.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/discipline/risk/risk-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/discipline/risk/risk.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/discipline/state-analysis/state-analysis-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/discipline/state-analysis/state-analysis.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/discipline/vandv/vandv-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/discipline/vandv/vandv.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/analysis/analysis-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/analysis/analysis.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/annotation/annotation.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/base/base-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/base/base.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/behavior/behavior-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/behavior/behavior.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/mission/mission-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/mission/mission.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/owl2-mof2/datatype-map.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/owl2-mof2/owl2-mof2-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/owl2-mof2/owl2-mof2.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/project/project-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/project/project.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/scenario/scenario-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/scenario/scenario.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/time/time-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/foundation/time/time.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/www.w3.org/1999/02/22-rdf-syntax-ns.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/www.w3.org/2000/01/rdf-schema.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/www.w3.org/2002/07/owl.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/purl.org/dc/elements/1.1/.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/PrimitiveTypes/20110701/PrimitiveTypes-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/PrimitiveTypes/20110701/PrimitiveTypes-metamodel.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/PrimitiveTypes/20110701/PrimitiveTypes.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/SysML/20140311/Metrology-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/SysML/20140311/Metrology-metamodel.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/SysML/20140311/Metrology.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/SysML/20140311/QUDV-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/SysML/20140311/QUDV-metamodel.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/SysML/20140311/QUDV.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/SysML/20140311/SysML-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/SysML/20140311/SysML-metamodel.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/SysML/20140311/SysML.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/UML/20110701/StandardProfileL2-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/UML/20110701/StandardProfileL2-metamodel.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/UML/20110701/StandardProfileL2.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/UML/20110701/UML-embedding.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/UML/20110701/UML-metamodel.oml
  /opt/local/imce/users/nfr/github.caesar/gov.nasa.jpl.imce.caesar.workflows/target/vocabulary-authored-imce/gov.nasa.jpl.imce.ontologies.public/converted-oml/imce.jpl.nasa.gov/www.omg.org/spec/UML/20110701/UML.oml
18/03/15 19:30:01 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/03/15 19:30:02 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
18/03/15 19:30:02 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
conversion=ConversionCommandFromOMLTextualSyntax
# => 60 OML files to convert...
# Loaded all OML resources (no EcoreUtil.resolveAll!) in 1s, 364ms.
### 1 Conversion Errors! ###
null
java.lang.NullPointerException
	at org.eclipse.emf.common.util.URI.createURIWithCache(URI.java:2567)
	at org.eclipse.emf.common.util.URI.createURI(URI.java:2445)
	at gov.nasa.jpl.imce.oml.converters.internal.package$$anonfun$toText$2$$anonfun$apply$20$$anonfun$4.apply(package.scala:339)
	at gov.nasa.jpl.imce.oml.converters.internal.package$$anonfun$toText$2$$anonfun$apply$20$$anonfun$4.apply(package.scala:335)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at gov.nasa.jpl.imce.oml.converters.internal.package$$anonfun$toText$2$$anonfun$apply$20.apply(package.scala:335)
	at gov.nasa.jpl.imce.oml.converters.internal.package$$anonfun$toText$2$$anonfun$apply$20.apply(package.scala:332)
	at scalaz.$bslash$div.map(Either.scala:112)
	at gov.nasa.jpl.imce.oml.converters.internal.package$$anonfun$toText$2.apply(package.scala:332)
	at gov.nasa.jpl.imce.oml.converters.internal.package$$anonfun$toText$2.apply(package.scala:329)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at gov.nasa.jpl.imce.oml.converters.internal.package$.toText(package.scala:329)
	at gov.nasa.jpl.imce.oml.converters.internal.package$$anonfun$outputConversions$1.apply(package.scala:259)
	at gov.nasa.jpl.imce.oml.converters.internal.package$$anonfun$outputConversions$1.apply(package.scala:251)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at gov.nasa.jpl.imce.oml.converters.internal.package$.outputConversions(package.scala:251)
	at gov.nasa.jpl.imce.oml.converters.internal.package$$anonfun$process$2$$anonfun$apply$2$$anonfun$apply$4.apply(package.scala:216)
	at gov.nasa.jpl.imce.oml.converters.internal.package$$anonfun$process$2$$anonfun$apply$2$$anonfun$apply$4.apply(package.scala:214)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at gov.nasa.jpl.imce.oml.converters.internal.package$$anonfun$process$2$$anonfun$apply$2.apply(package.scala:214)
	at gov.nasa.jpl.imce.oml.converters.internal.package$$anonfun$process$2$$anonfun$apply$2.apply(package.scala:206)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at gov.nasa.jpl.imce.oml.converters.internal.package$$anonfun$process$2.apply(package.scala:206)
	at gov.nasa.jpl.imce.oml.converters.internal.package$$anonfun$process$2.apply(package.scala:201)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at gov.nasa.jpl.imce.oml.converters.internal.package$.process(package.scala:201)
	at gov.nasa.jpl.imce.oml.converters.ConversionCommandFromOMLTextualSyntax$$anonfun$convert$2.apply(ConversionCommandFromOMLTextualSyntax.scala:110)
	at gov.nasa.jpl.imce.oml.converters.ConversionCommandFromOMLTextualSyntax$$anonfun$convert$2.apply(ConversionCommandFromOMLTextualSyntax.scala:55)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at gov.nasa.jpl.imce.oml.converters.ConversionCommandFromOMLTextualSyntax$.convert(ConversionCommandFromOMLTextualSyntax.scala:55)
	at gov.nasa.jpl.imce.oml.converters.OMLConverter$.catalogInputConversion(OMLConverter.scala:651)
	at gov.nasa.jpl.imce.oml.converters.OMLConverter$.main(OMLConverter.scala:475)
	at gov.nasa.jpl.imce.oml.converters.OMLConverter.main(OMLConverter.scala)
```

**Comment by NicolasRouquette** [comment]
This problem was due to passing a folder instead of a legitimate catalog to the `-out:cat` converter option. Need better validation to avoid this problem.
